parameters:
#    library_genre.example.class: Library\GenreBundle\Example

services:
#    library_genre.example:
#        class: %library_genre.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
